# basic setting
workers: 16

# model setting
backbone: 'videomae'
regressor: 'mlp'
feature_dim: 768
projection_dim: 512

# dataset setting
dataset: 'SimSurgSkill'
data_root: '/home/mrunmay/scratch/ActionQualityAssessment/datasets'
batch_size_train: 4
batch_size_test: 4

# optimizer abd training setting
temperature: 1
lr: 0.001
epochs: 100